package com.team5.models;

import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.annotation.Id;

@Document(collection = "recharges")
public class Recharges {
    
    @Id
    private String id;  // Auto-generated by MongoDB
    private String memberId;  // Reference to Members collection
    private Double amount;    // Amount recharged
    private String date;      // Date of recharge (ISO 8601 format)

    // Constructors
    public Recharges() {}
    public Recharges(String memberId, Double amount, String date) {
        this.memberId = memberId;
        if (amount == null || amount <= 100 || amount > 2000) {
            throw new IllegalArgumentException("Amount must be > 100 and < 2000");
        }
        this.amount = amount;
        this.date = date;
    }
    // Getters and Setters
    public String getId() {
        return id;
    }   
    public void setId(String id) {
        this.id = id;
    }
    public String getMemberId() {
        return memberId;
    }
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }
    public Double getAmount() {
        return amount; 
    }
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getDate() {
        return date;
    }
    public void setDate(String date) {
        this.date = date;
    }
    @Override
    public String toString() {
        return "Recharges{" +
                "id='" + id + '\'' +
                ", memberId='" + memberId + '\'' +
                ", amount=" + amount +
                ", date='" + date + '\'' +
                '}';
    }
   
}
