package com.team5.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "members")
public class Members {

    @Id
    private String id;  // Auto-generated by MongoDB

    private String name;

    private String phone;  // Unique phone number

    private Double balance = 0.0; // Default 0, should be >0 and <5000

    // Constructors
    public Members() {}

    public Members(String name, String phone, Double balance) {
        this.name = name;
        this.phone = phone;
        setBalance(balance);  // validation via setter
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        if (balance == null) {
            this.balance = 0.0;
        } else if (balance >= 0 && balance < 5000) {
            this.balance = balance;
        } else {
            throw new IllegalArgumentException("Balance must be between 0 and 5000");
        }
    }
}
