package com.team5.models;

import org.springframework.data.mongodb.core.mapping.Document;

import jakarta.persistence.Id;

@Document(collection= "transactions")
public class Transactions {

    @Id
    private String id;  // Auto-generated by MongoDB
    private String memberId;  // Reference to Members collection
    private String gameId;    // Reference to Games collection
    private Double amount;    // Amount of the transaction
    private String date;      // Date of transaction (ISO 8601 format)

    // Constructors
    public Transactions() {}
    public Transactions(String memberId, String gameId, Double amount, String date) {
        this.memberId = memberId;
        this.gameId = gameId;
        this.amount = amount != null ? amount : 0.0;
        this.date = date;
    }
    // Getters and Setters
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
    public String getMemberId() {
        return memberId;
    }
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }
    public String getGameId() {
        return gameId;
    }
    public void setGameId(String gameId) {
        this.gameId = gameId;
    }
    public Double getAmount() {
        return amount; 
    }

    public void setAmount(Double amount) {
        this.amount = amount; 
    }
    public String getDate() {
        return date;
    }
    public void setDate(String date) {
        this.date = date;
    }


    
}
